<a href="https://colab.research.google.com/github/nitishpanda666/python_assignment1/blob/main/assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [6]:
df=pd.read_csv('/Book1.csv')
print(df)

    roll name   age  gen branch  sec
0    1.0    a  18.0    m    cse    a
1    2.0    b  18.0    f    cse    b
2    3.0    c  19.0    m    cse    c
3    4.0    d  22.0    f    cse    c
4    5.0    e  34.0    m    cse    c
5    6.0    f  21.0    m    cse    c
6    7.0    g  24.0    m    cse    c
7    8.0    h  54.0    m    cse    c
8    9.0    i  76.0    f    cse    c
9   10.0    j  42.0    m    cse    b
10   NaN  NaN   NaN  NaN    NaN  NaN
11   NaN  NaN   NaN  NaN    NaN  NaN
12   NaN  NaN   NaN  NaN    NaN  NaN
13   NaN  NaN   NaN  NaN    NaN  NaN
14   NaN  NaN   NaN  NaN    NaN  NaN
15   NaN  NaN   NaN  NaN    NaN  NaN
16   1.0  NaN   NaN  NaN    NaN  NaN

In [7]:
df.tail()

    roll name  age  gen branch  sec
12   NaN  NaN  NaN  NaN    NaN  NaN
13   NaN  NaN  NaN  NaN    NaN  NaN
14   NaN  NaN  NaN  NaN    NaN  NaN
15   NaN  NaN  NaN  NaN    NaN  NaN
16   1.0  NaN  NaN  NaN    NaN  NaN

In [8]:
df.head(7)

   roll name   age gen branch sec
0   1.0    a  18.0   m    cse   a
1   2.0    b  18.0   f    cse   b
2   3.0    c  19.0   m    cse   c
3   4.0    d  22.0   f    cse   c
4   5.0    e  34.0   m    cse   c
5   6.0    f  21.0   m    cse   c
6   7.0    g  24.0   m    cse   c

In [9]:
df.tail(6)

    roll name  age  gen branch  sec
11   NaN  NaN  NaN  NaN    NaN  NaN
12   NaN  NaN  NaN  NaN    NaN  NaN
13   NaN  NaN  NaN  NaN    NaN  NaN
14   NaN  NaN  NaN  NaN    NaN  NaN
15   NaN  NaN  NaN  NaN    NaN  NaN
16   1.0  NaN  NaN  NaN    NaN  NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    11 non-null     float64
 1   name    10 non-null     object
 2   age     10 non-null     float64
 3   gen     10 non-null     object
 4   branch  10 non-null     object
 5   sec     10 non-null     object
dtypes: float64(2), object(4)
memory usage: 948.0+ bytes

In [11]:
df.describe()

            roll        age
count  11.000000  10.000000
mean    5.090909  32.800000
std     3.176619  19.332184
min     1.000000  18.000000
25%     2.500000  19.500000
50%     5.000000  23.000000
75%     7.500000  40.000000
max    10.000000  76.000000

In [13]:
df.shape

(17, 6)

In [15]:
df.columns

Index(['roll', 'name', 'age', 'gen', 'branch', 'sec'], dtype='object')

In [16]:
df.dtypes

roll      float64
name       object
age       float64
gen        object
branch     object
sec        object
dtype: object

In [17]:
df.isnull()

     roll   name    age    gen  branch    sec
0   False  False  False  False   False  False
1   False  False  False  False   False  False
2   False  False  False  False   False  False
3   False  False  False  False   False  False
4   False  False  False  False   False  False
5   False  False  False  False   False  False
6   False  False  False  False   False  False
7   False  False  False  False   False  False
8   False  False  False  False   False  False
9   False  False  False  False   False  False
10   True   True   True   True    True   True
11   True   True   True   True    True   True
12   True   True   True   True    True   True
13   True   True   True   True    True   True
14   True   True   True   True    True   True
15   True   True   True   True    True   True
16  False   True   True   True    True   True

In [18]:
df.isnull().sum()

roll      6
name      7
age       7
gen       7
branch    7
sec       7
dtype: int64

In [20]:
df.iloc[0]

roll       1.0
name         a
age       18.0
gen          m
branch     cse
sec          a
Name: 0, dtype: object

In [22]:
ages=df['age']
print(ages)

0     18.0
1     18.0
2     19.0
3     22.0
4     34.0
5     21.0
6     24.0
7     54.0
8     76.0
9     42.0
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
15     NaN
16     NaN
Name: age, dtype: float64

In [26]:
adults=df[df['age'] >20]
print("the age which are more tha 20 are",adults)

the age which are more tha 20 are    roll name   age gen branch sec
3   4.0    d  22.0   f    cse   c
4   5.0    e  34.0   m    cse   c
5   6.0    f  21.0   m    cse   c
6   7.0    g  24.0   m    cse   c
7   8.0    h  54.0   m    cse   c
8   9.0    i  76.0   f    cse   c
9  10.0    j  42.0   m    cse   b

In [28]:
adults=df[df['age'].between(19,20)]
print(adults)

   roll name   age gen branch sec
2   3.0    c  19.0   m    cse   c

In [30]:
gender=df['gen']
gender

0       m
1       f
2       m
3       f
4       m
5       m
6       m
7       m
8       f
9       m
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
Name: gen, dtype: object

In [32]:
male=df[df['gen']=='m']
print(male)

   roll name   age gen branch sec
0   1.0    a  18.0   m    cse   a
2   3.0    c  19.0   m    cse   c
4   5.0    e  34.0   m    cse   c
5   6.0    f  21.0   m    cse   c
6   7.0    g  24.0   m    cse   c
7   8.0    h  54.0   m    cse   c
9  10.0    j  42.0   m    cse   b